#!/bin/zsh
# SSH agent(s)
SSH_ENV=$HOME/.ssh/environment

function start_agent {
     echo "Initialising new SSH agent..."
     /usr/bin/ssh-agent | sed 's/^echo/#echo/' >! ${SSH_ENV}
     chmod 600 ${SSH_ENV}
     . ${SSH_ENV} > /dev/null
     /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [[ -f /usr/bin/keychain || -f /usr/local/bin/keychain ]]; then
	eval `keychain --eval id_rsa`
elif [[ -f "${SSH_ENV}" ]]; then
     . ${SSH_ENV} > /dev/null
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent > /dev/null || {
         start_agent;
     }
else
     start_agent;
fi

. ~/.zsh/function
. ~/.zsh/zle
. ~/.zsh/style
. ~/.zsh/opts
. ~/.zsh/export
. ~/.zsh/alias
. ~/.zsh/profiles # TODO: load from pattern
. ~/.zsh/prompt

# Hostname custom configs (post "hook")
if [[ -f $HOME/.zsh/$(hostname -d) ]]; then
	source $HOME/.zsh/$(hostname -d)
fi
if [[ -f $HOME/.zsh/$(hostname -s) ]]; then
	source $HOME/.zsh/$(hostname -s)
fi
