#!/bin/zsh
#
# zsh specifics

# autoload
autoload -U compinit
compinit

autoload colors    
colors 

# ZSH built-in VCS (git, …) functions
autoload -Uz vcs_info

# history
HISTFILE=~/.history
HISTSIZE=300000
SAVEHIST=300000

source $HOME/.zsh/completion/git-flow-completion.zsh
