#!/bin/zsh
#
# vi keybindings
# Mode vim
bindkey -v

# On remappe pour le bépo
bindkey -a c vi-backward-char
bindkey -a r vi-forward-char
bindkey -a t vi-down-line-or-history
bindkey -a s vi-up-line-or-history
bindkey -a $ vi-end-of-line
bindkey -a 0 vi-digit-or-beginning-of-line 
bindkey -a h vi-change
bindkey -a H vi-change-eol
bindkey -a dd vi-change-whole-line
bindkey -a l vi-replace-chars
bindkey -a L vi-replace
bindkey -a k vi-substitute
